### ISSUE TITLE
Rename and/or link to real python-gnupg

### ISSUE THREAD

**Issue by leo-labs** [isislovecruft/python-gnupg#113] opened 2015-07-05 09:41 UTC
Since python-gnupg is developed at https://bitbucket.org/vinay.sajip/python-gnupg/overview please rename and link to this page.

This github repository may confuse people!

**Comment by euklid** [comment] 2015-07-05 09:42
+1

**Comment by Kahn** [comment] 2015-07-05 22:15
I agree it is confusing but I switched to using this version of python gnupg after Vinay still has not released in 2015. There are some terrible hacks in code now to handle detecting the two libraries so I still agree it would be better to be explicit with the version differences via a rename.

**Comment by leo-labs** [comment] 2015-07-06 17:04
I have the feeling that having two versions is bad. I am not sure why you are not merging his changes (or do you?) and the other way around. I am pretty sure that the python community could profit from merging your fork back into 3.8.

And in terms of increasing the distribution of encryption this is an extra barrier.

Btw.: His master branch is working pretty well for me, though it's not released yet.

**Comment by torfuspolymorphus** [comment] 2015-07-15 14:21
+1 for merging the two projects if this is in any way possible. If it's not possible, +1 for a new name.

**Comment by isislovecruft** [comment] 2015-09-07 21:40
Duplicate of #47

**Closed by isislovecruft** 2015-09-07 21:40 UTC
